#bin/bash

# This is a test program about special characters which most used of shell.
echo "************************************************************************"
echo "'\$$' is the PID of shell itself."
echo "'\$$' is $$"
echo "************************************************************************"
echo "'\$!' is the PID of the latest running background process."
echo "'\$!' is $! "
echo "************************************************************************"
echo "'\$?' is the return code of the lastest running process."
echo "'\$?' is $?"
echo "************************************************************************"
echo "'\$-' is a display of Flag which Set set."
echo "'\$-' is $-"
echo "************************************************************************"
echo "'\$*' is the args formating \"\$1 \$12 ... \""
echo "'\$*' is $*"
echo "************************************************************************"
echo "'\$@' is the args formating \"\$1\" \"\$2\" ... "
echo "'\$@' is $@"
echo "************************************************************************"
echo "'\$#' is the number of args."
echo "'\$#' is $#"
echo "************************************************************************"
echo "'\$0' is the name of shell file."
echo "'\$0' is $0"
echo "************************************************************************"
echo "'\$1 ~ \$n' is respective args."
echo "'\$1' is $1"
echo "'\$2' is $2"
echo "************************************************************************"
